name: Package build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade build
      - name: Build package
        run: |
          python -m build
      - name: Upload build package
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*


  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built package
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
